version: '3'
services:
  app:
    build:
      context: .
      args:
        NODE_ENV: production
    depends_on:
      - flask
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules

  flask:
    build: ./api
    ports:
      - '5000:80'
    environment:
      - FLASK_APP=app/api.py
      - 'RUN=flask run --host=0.0.0.0 --port=80'